{* DO NOT EDIT THIS FILE! Use an override template instead.
    content/datatype/edit/cjwnewsletterlist.tpl
*}
{def $attribute_base='ContentObjectAttribute'
     $datatype_name='cjwnewsletteredition'
     $edition_object = $attribute.content}

<hr>

{*$edition_object|attribute(show)*}

<h2>Status:</h2>
<p> {$edition_object.status|wash} </p>

{include uri="design:includes/cjwnewsletteredition_preview.tpl" newsletter_edition_attribute=$attribute}

{undef $attribute_base $datatype_name $edition_object}